site_name: NetworkServices v5.0.2-beta-1+20220222
site_url: http://byron.github.io/google-apis-rs/google-networkservices1-cli
site_description: A complete library to interact with NetworkServices (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/networkservices1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Edge Cache Keysets Get Iam Policy': 'projects_locations-edge-cache-keysets-get-iam-policy.md'
    - 'Locations Edge Cache Keysets Set Iam Policy': 'projects_locations-edge-cache-keysets-set-iam-policy.md'
    - 'Locations Edge Cache Keysets Test Iam Permissions': 'projects_locations-edge-cache-keysets-test-iam-permissions.md'
    - 'Locations Edge Cache Origins Get Iam Policy': 'projects_locations-edge-cache-origins-get-iam-policy.md'
    - 'Locations Edge Cache Origins Set Iam Policy': 'projects_locations-edge-cache-origins-set-iam-policy.md'
    - 'Locations Edge Cache Origins Test Iam Permissions': 'projects_locations-edge-cache-origins-test-iam-permissions.md'
    - 'Locations Edge Cache Services Get Iam Policy': 'projects_locations-edge-cache-services-get-iam-policy.md'
    - 'Locations Edge Cache Services Set Iam Policy': 'projects_locations-edge-cache-services-set-iam-policy.md'
    - 'Locations Edge Cache Services Test Iam Permissions': 'projects_locations-edge-cache-services-test-iam-permissions.md'
    - 'Locations Endpoint Policies Create': 'projects_locations-endpoint-policies-create.md'
    - 'Locations Endpoint Policies Delete': 'projects_locations-endpoint-policies-delete.md'
    - 'Locations Endpoint Policies Get': 'projects_locations-endpoint-policies-get.md'
    - 'Locations Endpoint Policies Get Iam Policy': 'projects_locations-endpoint-policies-get-iam-policy.md'
    - 'Locations Endpoint Policies List': 'projects_locations-endpoint-policies-list.md'
    - 'Locations Endpoint Policies Patch': 'projects_locations-endpoint-policies-patch.md'
    - 'Locations Endpoint Policies Set Iam Policy': 'projects_locations-endpoint-policies-set-iam-policy.md'
    - 'Locations Endpoint Policies Test Iam Permissions': 'projects_locations-endpoint-policies-test-iam-permissions.md'
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

