site_name: adsense v5.0.2-beta-1+20220304
site_url: http://byron.github.io/google-apis-rs/google-adsense2-cli
site_description: A complete library to interact with adsense (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/adsense2-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Accounts':
    - 'Adclients Adunits Get': 'accounts_adclients-adunits-get.md'
    - 'Adclients Adunits Get Adcode': 'accounts_adclients-adunits-get-adcode.md'
    - 'Adclients Adunits List': 'accounts_adclients-adunits-list.md'
    - 'Adclients Adunits List Linked Custom Channels': 'accounts_adclients-adunits-list-linked-custom-channels.md'
    - 'Adclients Customchannels Get': 'accounts_adclients-customchannels-get.md'
    - 'Adclients Customchannels List': 'accounts_adclients-customchannels-list.md'
    - 'Adclients Customchannels List Linked Ad Units': 'accounts_adclients-customchannels-list-linked-ad-units.md'
    - 'Adclients Get Adcode': 'accounts_adclients-get-adcode.md'
    - 'Adclients List': 'accounts_adclients-list.md'
    - 'Adclients Urlchannels List': 'accounts_adclients-urlchannels-list.md'
    - 'Alerts List': 'accounts_alerts-list.md'
    - 'Get': 'accounts_get.md'
    - 'List': 'accounts_list.md'
    - 'List Child Accounts': 'accounts_list-child-accounts.md'
    - 'Payments List': 'accounts_payments-list.md'
    - 'Reports Generate': 'accounts_reports-generate.md'
    - 'Reports Generate Csv': 'accounts_reports-generate-csv.md'
    - 'Reports Saved Generate': 'accounts_reports-saved-generate.md'
    - 'Reports Saved Generate Csv': 'accounts_reports-saved-generate-csv.md'
    - 'Reports Saved List': 'accounts_reports-saved-list.md'
    - 'Sites Get': 'accounts_sites-get.md'
    - 'Sites List': 'accounts_sites-list.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

