site_name: Chrome Policy v5.0.2-beta-1+20220305
site_url: http://byron.github.io/google-apis-rs/google-chromepolicy1-cli
site_description: A complete library to interact with Chrome Policy (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/chromepolicy1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Customers':
    - 'Policies Orgunits Batch Inherit': 'customers_policies-orgunits-batch-inherit.md'
    - 'Policies Orgunits Batch Modify': 'customers_policies-orgunits-batch-modify.md'
    - 'Policies Resolve': 'customers_policies-resolve.md'
    - 'Policy Schemas Get': 'customers_policy-schemas-get.md'
    - 'Policy Schemas List': 'customers_policy-schemas-list.md'
- 'Media':
    - 'Upload': 'media_upload.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

