site_name: Game Services v5.0.2-beta-1+20220223
site_url: http://byron.github.io/google-apis-rs/google-gameservices1-cli
site_description: A complete library to interact with Game Services (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/gameservices1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Game Server Deployments Configs Create': 'projects_locations-game-server-deployments-configs-create.md'
    - 'Locations Game Server Deployments Configs Delete': 'projects_locations-game-server-deployments-configs-delete.md'
    - 'Locations Game Server Deployments Configs Get': 'projects_locations-game-server-deployments-configs-get.md'
    - 'Locations Game Server Deployments Configs List': 'projects_locations-game-server-deployments-configs-list.md'
    - 'Locations Game Server Deployments Create': 'projects_locations-game-server-deployments-create.md'
    - 'Locations Game Server Deployments Delete': 'projects_locations-game-server-deployments-delete.md'
    - 'Locations Game Server Deployments Fetch Deployment State': 'projects_locations-game-server-deployments-fetch-deployment-state.md'
    - 'Locations Game Server Deployments Get': 'projects_locations-game-server-deployments-get.md'
    - 'Locations Game Server Deployments Get Iam Policy': 'projects_locations-game-server-deployments-get-iam-policy.md'
    - 'Locations Game Server Deployments Get Rollout': 'projects_locations-game-server-deployments-get-rollout.md'
    - 'Locations Game Server Deployments List': 'projects_locations-game-server-deployments-list.md'
    - 'Locations Game Server Deployments Patch': 'projects_locations-game-server-deployments-patch.md'
    - 'Locations Game Server Deployments Preview Rollout': 'projects_locations-game-server-deployments-preview-rollout.md'
    - 'Locations Game Server Deployments Set Iam Policy': 'projects_locations-game-server-deployments-set-iam-policy.md'
    - 'Locations Game Server Deployments Test Iam Permissions': 'projects_locations-game-server-deployments-test-iam-permissions.md'
    - 'Locations Game Server Deployments Update Rollout': 'projects_locations-game-server-deployments-update-rollout.md'
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Realms Create': 'projects_locations-realms-create.md'
    - 'Locations Realms Delete': 'projects_locations-realms-delete.md'
    - 'Locations Realms Game Server Clusters Create': 'projects_locations-realms-game-server-clusters-create.md'
    - 'Locations Realms Game Server Clusters Delete': 'projects_locations-realms-game-server-clusters-delete.md'
    - 'Locations Realms Game Server Clusters Get': 'projects_locations-realms-game-server-clusters-get.md'
    - 'Locations Realms Game Server Clusters List': 'projects_locations-realms-game-server-clusters-list.md'
    - 'Locations Realms Game Server Clusters Patch': 'projects_locations-realms-game-server-clusters-patch.md'
    - 'Locations Realms Game Server Clusters Preview Create': 'projects_locations-realms-game-server-clusters-preview-create.md'
    - 'Locations Realms Game Server Clusters Preview Delete': 'projects_locations-realms-game-server-clusters-preview-delete.md'
    - 'Locations Realms Game Server Clusters Preview Update': 'projects_locations-realms-game-server-clusters-preview-update.md'
    - 'Locations Realms Get': 'projects_locations-realms-get.md'
    - 'Locations Realms List': 'projects_locations-realms-list.md'
    - 'Locations Realms Patch': 'projects_locations-realms-patch.md'
    - 'Locations Realms Preview Update': 'projects_locations-realms-preview-update.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

