site_name: networkconnectivity v5.0.2-beta-1+20220210
site_url: http://byron.github.io/google-apis-rs/google-networkconnectivity1-cli
site_description: A complete library to interact with networkconnectivity (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/networkconnectivity1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations Global Hubs Create': 'projects_locations-global-hubs-create.md'
    - 'Locations Global Hubs Delete': 'projects_locations-global-hubs-delete.md'
    - 'Locations Global Hubs Get': 'projects_locations-global-hubs-get.md'
    - 'Locations Global Hubs Get Iam Policy': 'projects_locations-global-hubs-get-iam-policy.md'
    - 'Locations Global Hubs List': 'projects_locations-global-hubs-list.md'
    - 'Locations Global Hubs Patch': 'projects_locations-global-hubs-patch.md'
    - 'Locations Global Hubs Set Iam Policy': 'projects_locations-global-hubs-set-iam-policy.md'
    - 'Locations Global Hubs Test Iam Permissions': 'projects_locations-global-hubs-test-iam-permissions.md'
    - 'Locations Global Policy Based Routes Get Iam Policy': 'projects_locations-global-policy-based-routes-get-iam-policy.md'
    - 'Locations Global Policy Based Routes Set Iam Policy': 'projects_locations-global-policy-based-routes-set-iam-policy.md'
    - 'Locations Global Policy Based Routes Test Iam Permissions': 'projects_locations-global-policy-based-routes-test-iam-permissions.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Spokes Create': 'projects_locations-spokes-create.md'
    - 'Locations Spokes Delete': 'projects_locations-spokes-delete.md'
    - 'Locations Spokes Get': 'projects_locations-spokes-get.md'
    - 'Locations Spokes Get Iam Policy': 'projects_locations-spokes-get-iam-policy.md'
    - 'Locations Spokes List': 'projects_locations-spokes-list.md'
    - 'Locations Spokes Patch': 'projects_locations-spokes-patch.md'
    - 'Locations Spokes Set Iam Policy': 'projects_locations-spokes-set-iam-policy.md'
    - 'Locations Spokes Test Iam Permissions': 'projects_locations-spokes-test-iam-permissions.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

