site_name: Chrome Management v5.0.2-beta-1+20220305
site_url: http://byron.github.io/google-apis-rs/google-chromemanagement1-cli
site_description: A complete library to interact with Chrome Management (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/chromemanagement1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Customers':
    - 'Apps Android Get': 'customers_apps-android-get.md'
    - 'Apps Chrome Get': 'customers_apps-chrome-get.md'
    - 'Apps Count Chrome App Requests': 'customers_apps-count-chrome-app-requests.md'
    - 'Apps Web Get': 'customers_apps-web-get.md'
    - 'Reports Count Chrome Versions': 'customers_reports-count-chrome-versions.md'
    - 'Reports Count Installed Apps': 'customers_reports-count-installed-apps.md'
    - 'Reports Find Installed App Devices': 'customers_reports-find-installed-app-devices.md'
    - 'Telemetry Devices List': 'customers_telemetry-devices-list.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

