site_name: Cloud Run v5.0.2-beta-1+20220225
site_url: http://byron.github.io/google-apis-rs/google-run2-cli
site_description: A complete library to interact with Cloud Run (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/run2-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Services Create': 'projects_locations-services-create.md'
    - 'Locations Services Delete': 'projects_locations-services-delete.md'
    - 'Locations Services Get': 'projects_locations-services-get.md'
    - 'Locations Services Get Iam Policy': 'projects_locations-services-get-iam-policy.md'
    - 'Locations Services List': 'projects_locations-services-list.md'
    - 'Locations Services Patch': 'projects_locations-services-patch.md'
    - 'Locations Services Revisions Delete': 'projects_locations-services-revisions-delete.md'
    - 'Locations Services Revisions Get': 'projects_locations-services-revisions-get.md'
    - 'Locations Services Revisions List': 'projects_locations-services-revisions-list.md'
    - 'Locations Services Set Iam Policy': 'projects_locations-services-set-iam-policy.md'
    - 'Locations Services Test Iam Permissions': 'projects_locations-services-test-iam-permissions.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

