site_name: OrgPolicy API v5.0.2-beta-1+20220305
site_url: http://byron.github.io/google-apis-rs/google-orgpolicy2-cli
site_description: A complete library to interact with OrgPolicy API (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/orgpolicy2-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Folders':
    - 'Constraints List': 'folders_constraints-list.md'
    - 'Policies Create': 'folders_policies-create.md'
    - 'Policies Delete': 'folders_policies-delete.md'
    - 'Policies Get': 'folders_policies-get.md'
    - 'Policies Get Effective Policy': 'folders_policies-get-effective-policy.md'
    - 'Policies List': 'folders_policies-list.md'
    - 'Policies Patch': 'folders_policies-patch.md'
- 'Organizations':
    - 'Constraints List': 'organizations_constraints-list.md'
    - 'Policies Create': 'organizations_policies-create.md'
    - 'Policies Delete': 'organizations_policies-delete.md'
    - 'Policies Get': 'organizations_policies-get.md'
    - 'Policies Get Effective Policy': 'organizations_policies-get-effective-policy.md'
    - 'Policies List': 'organizations_policies-list.md'
    - 'Policies Patch': 'organizations_policies-patch.md'
- 'Projects':
    - 'Constraints List': 'projects_constraints-list.md'
    - 'Policies Create': 'projects_policies-create.md'
    - 'Policies Delete': 'projects_policies-delete.md'
    - 'Policies Get': 'projects_policies-get.md'
    - 'Policies Get Effective Policy': 'projects_policies-get-effective-policy.md'
    - 'Policies List': 'projects_policies-list.md'
    - 'Policies Patch': 'projects_policies-patch.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

