site_name: baremetalsolution v5.0.2-beta-1+20220209
site_url: http://byron.github.io/google-apis-rs/google-baremetalsolution2-cli
site_description: A complete library to interact with baremetalsolution (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/baremetalsolution2-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations Instances Get': 'projects_locations-instances-get.md'
    - 'Locations Instances List': 'projects_locations-instances-list.md'
    - 'Locations Instances Patch': 'projects_locations-instances-patch.md'
    - 'Locations Instances Reset': 'projects_locations-instances-reset.md'
    - 'Locations Instances Start': 'projects_locations-instances-start.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Networks Get': 'projects_locations-networks-get.md'
    - 'Locations Networks List': 'projects_locations-networks-list.md'
    - 'Locations Networks List Network Usage': 'projects_locations-networks-list-network-usage.md'
    - 'Locations Networks Patch': 'projects_locations-networks-patch.md'
    - 'Locations Nfs Shares Get': 'projects_locations-nfs-shares-get.md'
    - 'Locations Nfs Shares List': 'projects_locations-nfs-shares-list.md'
    - 'Locations Nfs Shares Patch': 'projects_locations-nfs-shares-patch.md'
    - 'Locations Provisioning Configs Submit': 'projects_locations-provisioning-configs-submit.md'
    - 'Locations Provisioning Quotas List': 'projects_locations-provisioning-quotas-list.md'
    - 'Locations Snapshot Schedule Policies Create': 'projects_locations-snapshot-schedule-policies-create.md'
    - 'Locations Snapshot Schedule Policies Delete': 'projects_locations-snapshot-schedule-policies-delete.md'
    - 'Locations Snapshot Schedule Policies Get': 'projects_locations-snapshot-schedule-policies-get.md'
    - 'Locations Snapshot Schedule Policies List': 'projects_locations-snapshot-schedule-policies-list.md'
    - 'Locations Snapshot Schedule Policies Patch': 'projects_locations-snapshot-schedule-policies-patch.md'
    - 'Locations Volumes Get': 'projects_locations-volumes-get.md'
    - 'Locations Volumes List': 'projects_locations-volumes-list.md'
    - 'Locations Volumes Luns Get': 'projects_locations-volumes-luns-get.md'
    - 'Locations Volumes Luns List': 'projects_locations-volumes-luns-list.md'
    - 'Locations Volumes Patch': 'projects_locations-volumes-patch.md'
    - 'Locations Volumes Snapshots Create': 'projects_locations-volumes-snapshots-create.md'
    - 'Locations Volumes Snapshots Delete': 'projects_locations-volumes-snapshots-delete.md'
    - 'Locations Volumes Snapshots Get': 'projects_locations-volumes-snapshots-get.md'
    - 'Locations Volumes Snapshots List': 'projects_locations-volumes-snapshots-list.md'
    - 'Locations Volumes Snapshots Restore Volume Snapshot': 'projects_locations-volumes-snapshots-restore-volume-snapshot.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

