site_name: Cloud Dataplex v5.0.2-beta-1+20220223
site_url: http://byron.github.io/google-apis-rs/google-dataplex1-cli
site_description: A complete library to interact with Cloud Dataplex (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/dataplex1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations Lakes Actions List': 'projects_locations-lakes-actions-list.md'
    - 'Locations Lakes Content Get Iam Policy': 'projects_locations-lakes-content-get-iam-policy.md'
    - 'Locations Lakes Content Set Iam Policy': 'projects_locations-lakes-content-set-iam-policy.md'
    - 'Locations Lakes Content Test Iam Permissions': 'projects_locations-lakes-content-test-iam-permissions.md'
    - 'Locations Lakes Contentitems Create': 'projects_locations-lakes-contentitems-create.md'
    - 'Locations Lakes Contentitems Delete': 'projects_locations-lakes-contentitems-delete.md'
    - 'Locations Lakes Contentitems Get': 'projects_locations-lakes-contentitems-get.md'
    - 'Locations Lakes Contentitems List': 'projects_locations-lakes-contentitems-list.md'
    - 'Locations Lakes Contentitems Patch': 'projects_locations-lakes-contentitems-patch.md'
    - 'Locations Lakes Create': 'projects_locations-lakes-create.md'
    - 'Locations Lakes Delete': 'projects_locations-lakes-delete.md'
    - 'Locations Lakes Environments Create': 'projects_locations-lakes-environments-create.md'
    - 'Locations Lakes Environments Delete': 'projects_locations-lakes-environments-delete.md'
    - 'Locations Lakes Environments Get': 'projects_locations-lakes-environments-get.md'
    - 'Locations Lakes Environments Get Iam Policy': 'projects_locations-lakes-environments-get-iam-policy.md'
    - 'Locations Lakes Environments List': 'projects_locations-lakes-environments-list.md'
    - 'Locations Lakes Environments Patch': 'projects_locations-lakes-environments-patch.md'
    - 'Locations Lakes Environments Sessions List': 'projects_locations-lakes-environments-sessions-list.md'
    - 'Locations Lakes Environments Set Iam Policy': 'projects_locations-lakes-environments-set-iam-policy.md'
    - 'Locations Lakes Environments Test Iam Permissions': 'projects_locations-lakes-environments-test-iam-permissions.md'
    - 'Locations Lakes Get': 'projects_locations-lakes-get.md'
    - 'Locations Lakes Get Iam Policy': 'projects_locations-lakes-get-iam-policy.md'
    - 'Locations Lakes List': 'projects_locations-lakes-list.md'
    - 'Locations Lakes Patch': 'projects_locations-lakes-patch.md'
    - 'Locations Lakes Set Iam Policy': 'projects_locations-lakes-set-iam-policy.md'
    - 'Locations Lakes Tasks Create': 'projects_locations-lakes-tasks-create.md'
    - 'Locations Lakes Tasks Delete': 'projects_locations-lakes-tasks-delete.md'
    - 'Locations Lakes Tasks Get': 'projects_locations-lakes-tasks-get.md'
    - 'Locations Lakes Tasks Get Iam Policy': 'projects_locations-lakes-tasks-get-iam-policy.md'
    - 'Locations Lakes Tasks Jobs Cancel': 'projects_locations-lakes-tasks-jobs-cancel.md'
    - 'Locations Lakes Tasks Jobs Get': 'projects_locations-lakes-tasks-jobs-get.md'
    - 'Locations Lakes Tasks Jobs List': 'projects_locations-lakes-tasks-jobs-list.md'
    - 'Locations Lakes Tasks List': 'projects_locations-lakes-tasks-list.md'
    - 'Locations Lakes Tasks Patch': 'projects_locations-lakes-tasks-patch.md'
    - 'Locations Lakes Tasks Set Iam Policy': 'projects_locations-lakes-tasks-set-iam-policy.md'
    - 'Locations Lakes Tasks Test Iam Permissions': 'projects_locations-lakes-tasks-test-iam-permissions.md'
    - 'Locations Lakes Test Iam Permissions': 'projects_locations-lakes-test-iam-permissions.md'
    - 'Locations Lakes Zones Actions List': 'projects_locations-lakes-zones-actions-list.md'
    - 'Locations Lakes Zones Assets Actions List': 'projects_locations-lakes-zones-assets-actions-list.md'
    - 'Locations Lakes Zones Assets Create': 'projects_locations-lakes-zones-assets-create.md'
    - 'Locations Lakes Zones Assets Delete': 'projects_locations-lakes-zones-assets-delete.md'
    - 'Locations Lakes Zones Assets Get': 'projects_locations-lakes-zones-assets-get.md'
    - 'Locations Lakes Zones Assets Get Iam Policy': 'projects_locations-lakes-zones-assets-get-iam-policy.md'
    - 'Locations Lakes Zones Assets List': 'projects_locations-lakes-zones-assets-list.md'
    - 'Locations Lakes Zones Assets Patch': 'projects_locations-lakes-zones-assets-patch.md'
    - 'Locations Lakes Zones Assets Set Iam Policy': 'projects_locations-lakes-zones-assets-set-iam-policy.md'
    - 'Locations Lakes Zones Assets Test Iam Permissions': 'projects_locations-lakes-zones-assets-test-iam-permissions.md'
    - 'Locations Lakes Zones Create': 'projects_locations-lakes-zones-create.md'
    - 'Locations Lakes Zones Delete': 'projects_locations-lakes-zones-delete.md'
    - 'Locations Lakes Zones Entities Create': 'projects_locations-lakes-zones-entities-create.md'
    - 'Locations Lakes Zones Entities Delete': 'projects_locations-lakes-zones-entities-delete.md'
    - 'Locations Lakes Zones Entities Get': 'projects_locations-lakes-zones-entities-get.md'
    - 'Locations Lakes Zones Entities List': 'projects_locations-lakes-zones-entities-list.md'
    - 'Locations Lakes Zones Entities Partitions Create': 'projects_locations-lakes-zones-entities-partitions-create.md'
    - 'Locations Lakes Zones Entities Partitions Delete': 'projects_locations-lakes-zones-entities-partitions-delete.md'
    - 'Locations Lakes Zones Entities Partitions Get': 'projects_locations-lakes-zones-entities-partitions-get.md'
    - 'Locations Lakes Zones Entities Partitions List': 'projects_locations-lakes-zones-entities-partitions-list.md'
    - 'Locations Lakes Zones Entities Update': 'projects_locations-lakes-zones-entities-update.md'
    - 'Locations Lakes Zones Get': 'projects_locations-lakes-zones-get.md'
    - 'Locations Lakes Zones Get Iam Policy': 'projects_locations-lakes-zones-get-iam-policy.md'
    - 'Locations Lakes Zones List': 'projects_locations-lakes-zones-list.md'
    - 'Locations Lakes Zones Patch': 'projects_locations-lakes-zones-patch.md'
    - 'Locations Lakes Zones Set Iam Policy': 'projects_locations-lakes-zones-set-iam-policy.md'
    - 'Locations Lakes Zones Test Iam Permissions': 'projects_locations-lakes-zones-test-iam-permissions.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

