site_name: Document v5.0.2-beta-1+20220226
site_url: http://byron.github.io/google-apis-rs/google-documentai1-cli
site_description: A complete library to interact with Document (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/documentai1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Operations':
    - 'Delete': 'operations_delete.md'
- 'Projects':
    - 'Locations Fetch Processor Types': 'projects_locations-fetch-processor-types.md'
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Processors Batch Process': 'projects_locations-processors-batch-process.md'
    - 'Locations Processors Create': 'projects_locations-processors-create.md'
    - 'Locations Processors Delete': 'projects_locations-processors-delete.md'
    - 'Locations Processors Disable': 'projects_locations-processors-disable.md'
    - 'Locations Processors Enable': 'projects_locations-processors-enable.md'
    - 'Locations Processors Get': 'projects_locations-processors-get.md'
    - 'Locations Processors Human Review Config Review Document': 'projects_locations-processors-human-review-config-review-document.md'
    - 'Locations Processors List': 'projects_locations-processors-list.md'
    - 'Locations Processors Process': 'projects_locations-processors-process.md'
    - 'Locations Processors Processor Versions Batch Process': 'projects_locations-processors-processor-versions-batch-process.md'
    - 'Locations Processors Processor Versions Delete': 'projects_locations-processors-processor-versions-delete.md'
    - 'Locations Processors Processor Versions Deploy': 'projects_locations-processors-processor-versions-deploy.md'
    - 'Locations Processors Processor Versions Get': 'projects_locations-processors-processor-versions-get.md'
    - 'Locations Processors Processor Versions List': 'projects_locations-processors-processor-versions-list.md'
    - 'Locations Processors Processor Versions Process': 'projects_locations-processors-processor-versions-process.md'
    - 'Locations Processors Processor Versions Undeploy': 'projects_locations-processors-processor-versions-undeploy.md'
    - 'Locations Processors Set Default Processor Version': 'projects_locations-processors-set-default-processor-version.md'
    - 'Operations Get': 'projects_operations-get.md'
- 'Uiv1beta3':
    - 'Projects Locations Get': 'uiv1beta3_projects-locations-get.md'
    - 'Projects Locations List': 'uiv1beta3_projects-locations-list.md'
    - 'Projects Locations Operations Cancel': 'uiv1beta3_projects-locations-operations-cancel.md'
    - 'Projects Locations Operations Get': 'uiv1beta3_projects-locations-operations-get.md'
    - 'Projects Locations Operations List': 'uiv1beta3_projects-locations-operations-list.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

