site_name: Texttospeech v5.0.2-beta-1+20220228
site_url: http://byron.github.io/google-apis-rs/google-texttospeech1-cli
site_description: A complete library to interact with Texttospeech (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/texttospeech1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Text':
    - 'Synthesize': 'text_synthesize.md'
- 'Voices':
    - 'List': 'voices_list.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

